# Generated by Django 2.2.7 on 2019-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank='False', max_length=1000, null='False', verbose_name='название')),
                ('short_name', models.CharField(blank='False', max_length=1000, null='False', verbose_name='название')),
                ('host', models.CharField(blank='False', max_length=1000, null='False', verbose_name='название')),
                ('data_base', models.CharField(blank='False', max_length=1000, null='False', verbose_name='название')),
                ('password', models.CharField(blank='False', max_length=32, null='False')),
            ],
        ),
    ]
