# Generated by Django 2.2.7 on 2019-11-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0002_osp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col2', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col3', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col4', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col5', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col6', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col7', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col8', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col9', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col10', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col11', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col12', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col13', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col14', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col15', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Fssp_filter')),
                ('osp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Osp')),
            ],
        ),
        migrations.CreateModel(
            name='Vitrina_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col2', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col3', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col4', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col5', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col6', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col7', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col8', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col9', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col10', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col11', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col12', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col13', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col14', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col15', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('vitrina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Vitrina')),
            ],
        ),
    ]
