# Generated by Django 2.2.7 on 2019-11-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0003_vitrina_vitrina_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitrina_fields',
            new_name='Vitrina_field',
        ),
    ]
