# Generated by Django 2.2.7 on 2019-11-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0004_auto_20191121_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fssp_filter',
            new_name='FsspFilter',
        ),
        migrations.RenameModel(
            old_name='Fssp_filter_cat',
            new_name='FsspFilterCat',
        ),
        migrations.RenameModel(
            old_name='Vitrina_field',
            new_name='VitrinaField',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col1',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col10',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col11',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col12',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col13',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col14',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col15',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col2',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col3',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col4',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col5',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col6',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col7',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col8',
        ),
        migrations.RemoveField(
            model_name='vitrina',
            name='col9',
        ),
        migrations.CreateModel(
            name='VitrinaValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col2', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col3', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col4', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col5', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col6', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col7', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col8', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col9', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col10', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col11', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col12', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col13', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col14', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('col15', models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col1')),
                ('osp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Osp')),
                ('vitrina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Vitrina')),
            ],
        ),
    ]
