# Generated by Django 2.2.7 on 2019-11-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0005_auto_20191124_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitrina',
            name='osp',
        ),
    ]
