# Generated by Django 2.2.7 on 2019-11-26 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0006_remove_vitrina_osp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='date_actual',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 14, 22, 40, 267301), null='False'),
            preserve_default='False',
        ),
    ]
