# Generated by Django 2.2.7 on 2019-11-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0007_vitrina_date_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='calc_field_name',
            field=models.BooleanField(default=True, null='False'),
            preserve_default='False',
        ),
    ]
