# Generated by Django 2.2.7 on 2019-12-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0008_vitrina_calc_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='custom_fields',
            field=models.BooleanField(default=False, null='False'),
            preserve_default='False',
        ),
        migrations.CreateModel(
            name='VitrinaCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_number', models.CharField(choices=[('col1', 'col1'), ('col2', 'col2'), ('col3', 'col3'), ('col4', 'col4'), ('col5', 'col5'), ('col6', 'col6'), ('col7', 'col7'), ('col8', 'col8'), ('col9', 'col9'), ('col10', 'col10'), ('col11', 'col11'), ('col12', 'col12'), ('col13', 'col13'), ('col14', 'col14'), ('col15', 'col15')], default='col1', max_length=10)),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.FsspFilter')),
                ('vitrina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fssp_mon.Vitrina')),
            ],
        ),
    ]
