# Generated by Django 2.2.7 on 2019-12-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0009_auto_20191209_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrina',
            name='name',
            field=models.CharField(blank='False', default='vitrina', max_length=1000, null='False', verbose_name='название'),
            preserve_default='False',
        ),
    ]
