# Generated by Django 2.2.7 on 2019-12-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0010_vitrina_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vitrinacustom',
            old_name='filer',
            new_name='filter',
        ),
    ]
