# Generated by Django 2.2.7 on 2019-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fssp_mon', '0011_auto_20191209_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrinacustom',
            name='width',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinafield',
            name='col16',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col16'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinafield',
            name='col17',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col17'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinafield',
            name='col18',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col18'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinafield',
            name='col19',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col19'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinafield',
            name='col20',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col20'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinavalue',
            name='col16',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col16'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinavalue',
            name='col17',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col17'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinavalue',
            name='col18',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col18'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinavalue',
            name='col19',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col19'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='vitrinavalue',
            name='col20',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col20'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='vitrinacustom',
            name='col_number',
            field=models.CharField(choices=[('col1', 'col1'), ('col2', 'col2'), ('col3', 'col3'), ('col4', 'col4'), ('col5', 'col5'), ('col6', 'col6'), ('col7', 'col7'), ('col8', 'col8'), ('col9', 'col9'), ('col10', 'col10'), ('col11', 'col11'), ('col12', 'col12'), ('col13', 'col13'), ('col14', 'col14'), ('col15', 'col15'), ('col16', 'col16'), ('col17', 'col17'), ('col18', 'col18'), ('col19', 'col19'), ('col20', 'col20')], default='col1', max_length=10),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col10',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col10'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col11',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col11'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col12',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col12'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col13',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col13'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col14',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col14'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col15',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col15'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col2',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col2'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col3',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col3'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col4',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col4'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col5',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col5'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col6',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col6'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col7',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col7'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col8',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col8'),
        ),
        migrations.AlterField(
            model_name='vitrinafield',
            name='col9',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col9'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col10',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col10'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col11',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col11'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col12',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col12'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col13',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col13'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col14',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col14'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col15',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col15'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col2',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col2'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col3',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col3'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col4',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col4'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col5',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col5'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col6',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col6'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col7',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col7'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col8',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col8'),
        ),
        migrations.AlterField(
            model_name='vitrinavalue',
            name='col9',
            field=models.CharField(blank='True', max_length=1000, null='True', verbose_name='Col9'),
        ),
    ]
