- hosts: localhost
  tasks:
  - name: build front
    shell: 'cd {{ path_to_front }} && npm run build'

  - name: reload service httpd, in all cases
    systemd:
      name: apache2
      state: stopped
  - name: reload service httpd, in all cases
    file:
      path: '{{ path_to_www }}'
      state: absent
  - name: reload service httpd, in all cases
    file:
      path: '{{ path_to_www }}' 
      state: directory
      
  - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
    archive:
      path: '{{  path_to_front }}/build/static'
      dest: /tmp/front.tgz      
  - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
    archive:
      path: '{{  path_to_front }}/../static'
      dest: /tmp/admin.tgz 

 
  - name: copy
    unarchive:
      src: /tmp/front.tgz  
      dest:  '{{ path_to_www }}'
      remote_src: yes
  - name: copy
    unarchive:
      src: /tmp/admin.tgz 
      dest:  '{{ path_to_www }}'
      remote_src: yes
  - name: reload service httpd, in all cases
    systemd:
      name: apache2
      state: started
      
