- name: Install & configure Hashicorp Consul cluster
  hosts: osp
  #become: yes
  gather_facts: yes
  pre_tasks:
    - name: Remove consul agents
      set_fact:
         mount: "{{ ansible_mounts  }}"
    - name: Debug
      template:
         src: 'free.json'
         dest: '{{ path_to_json }}/{{ ansible_host }}'
      delefate_to: localhost

