- name: Install & configure Hashicorp Consul cluster
  hosts: osp
  #become: yes
  gather_facts: yes
  pre_tasks:
    - name: Remove consul agents
      set_fact:
         mount: "{{ ansible_mounts  | dict2items(key_name='mount', value_name='/home/db') }}"
    - name: Debug
      debug:
         var: mount

