- hosts: localhost
  tasks:
 #install depends packages

 #install apache2
 #generate apache config
 #install wsgi_py apache mod
 #enable modules  
 #create mysqldb
 #create fssp_views_setting 
  #redis
  - name: Install the package redis
    apt:
      name: redis
    tags: [all] 
    
  - name: install python modules 
    shell: 'cd {{ path_to_home }} && python3 -m pip install -r ./requirements.txt'
    tags: [all]
  
  - name: Download nodejs
    get_url:
      url: https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz  
      dest: /tmp
      use_proxy: "{{ use_p  |default('no')}}"
      mode: '0440'
    tags: [all]
    
  - name: install nodejs
    unarchive:
       src: /tmp/node-v12.16.1-linux-x64.tar.xz
       dest:  '/usr'
       remote_src: yes
    tags: [all]

  - name: create celery conf dir
    file:
      path: '{{ item }}' 
      state: directory
    with_items: ['/etc/conf.d' , '/opt/celery' ]
    tags: [ all, celery ]
     
  - name: create celery service
    templates: 
      src: 'celery.service'
      dest: '/etc/system.d/system/celery.service'
    tags: [all, celery ]

  - name: create celery conf
    templates: 
      src: celery
      dest: '/etc/conf.d/celery'
    tags: [all, celery  ] 
