- hosts: localhost
  tasks:

- name: Download nodejs
  get_url:
    url: https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.xz  
    dest: /tmp
    mode: '0440'

  - name: install nodejs
    unarchive:
      src: /tmp/node-v12.16.1-linux-x64.tar.xz
      dest:  '/usr'
      remote_src: yes


